# application: buswhereru
# version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /.*
  script: start.app
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

